# This file configures the analyzer, which statically analyzes Dart code to

include: package:flutter_lints/flutter.yaml

linter:
  
  rules:
    avoid_print: false 
    prefer_single_quotes: true 
    curly_braces_in_flow_control_structures: false
